packages:
  - 'apps/*'
  - 'packages/*'
onlyBuiltDependencies:
  - sharp
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  sharp: set this to true or false
  unrs-resolver: true
