import { Module } from '@nestjs/common';
import {
  WorkflowController,
  RulesController,
  EventsController,
  SchedulerController,
  OrchestrationController,
} from './infrastructure/controllers';
import {
  WorkflowService,
  WorkflowExecutionService,
  WorkflowDefinitionService,
  WorkflowStateService,
  CompensationService,
  ApprovalService,
  TimerService,
  WorkflowPersistenceService,
  RuleService,
  RuleEvaluationService,
  DecisionService,
  ExpressionEngineService,
  PolicyService,
  RuleVersionService,
  SimulationService,
  EventPublisherService,
  EventSubscriberService,
  EventRouterService,
  EventReplayService,
  DeadLetterService,
  EventRetryService,
  CorrelationService,
  SubscriptionService,
  SchedulerService,
  JobExecutionService,
  CronService,
  CalendarService,
  MisfireHandlerService,
  DistributedLockService,
  LeaderElectionService,
  SchedulePersistenceService,
  // Orchestration Platform — 8 services
  ExecutionGraphService,
  ExecutionPersistenceService,
  OrchestrationService,
  RuntimeService,
  TriggerService,
  TemplateService,
  CheckpointService,
  OrchestrationCorrelationService,
} from './application/services';

@Module({
  controllers: [
    WorkflowController,
    RulesController,
    EventsController,
    SchedulerController,
    // Orchestration Platform
    OrchestrationController,
  ],
  providers: [
    // Workflow Engine
    WorkflowService,
    WorkflowExecutionService,
    WorkflowDefinitionService,
    WorkflowStateService,
    CompensationService,
    ApprovalService,
    TimerService,
    WorkflowPersistenceService,
    // Business Rules Engine
    RuleService,
    RuleEvaluationService,
    DecisionService,
    ExpressionEngineService,
    PolicyService,
    RuleVersionService,
    SimulationService,
    // Event Processing Platform
    EventPublisherService,
    EventSubscriberService,
    EventRouterService,
    EventReplayService,
    DeadLetterService,
    EventRetryService,
    CorrelationService,
    SubscriptionService,
    // Scheduler Platform
    DistributedLockService,
    LeaderElectionService,
    CronService,
    CalendarService,
    MisfireHandlerService,
    SchedulePersistenceService,
    JobExecutionService,
    SchedulerService,
    // Orchestration Platform (registered dependency-first)
    ExecutionGraphService,
    ExecutionPersistenceService,
    OrchestrationCorrelationService,
    CheckpointService,
    TriggerService,
    TemplateService,
    RuntimeService,
    OrchestrationService,
  ],
  exports: [
    // Workflow Engine exports
    WorkflowService,
    WorkflowExecutionService,
    // Rules Engine exports
    RuleService,
    RuleEvaluationService,
    // Event Platform exports
    EventPublisherService,
    SubscriptionService,
    // Scheduler Platform exports
    SchedulerService,
    JobExecutionService,
    CronService,
    // Orchestration Platform exports
    OrchestrationService,
    RuntimeService,
    TriggerService,
    TemplateService,
  ],
})
export class AutomationModule {}
