import { Module } from '@nestjs/common';
import { WorkflowController, RulesController, EventsController } from './infrastructure/controllers';
import {
  WorkflowService,
  WorkflowExecutionService,
  WorkflowDefinitionService,
  WorkflowStateService,
  CompensationService,
  ApprovalService,
  TimerService,
  WorkflowPersistenceService,
  RuleService,
  RuleEvaluationService,
  DecisionService,
  ExpressionEngineService,
  PolicyService,
  RuleVersionService,
  SimulationService,
  EventPublisherService,
  EventSubscriberService,
  EventRouterService,
  EventReplayService,
  DeadLetterService,
  RetryService,
  CorrelationService,
  SubscriptionService,
} from './application/services';

@Module({
  controllers: [
    WorkflowController,
    RulesController,
    EventsController,
  ],
  providers: [
    WorkflowService,
    WorkflowExecutionService,
    WorkflowDefinitionService,
    WorkflowStateService,
    CompensationService,
    ApprovalService,
    TimerService,
    WorkflowPersistenceService,
    RuleService,
    RuleEvaluationService,
    DecisionService,
    ExpressionEngineService,
    PolicyService,
    RuleVersionService,
    SimulationService,
    EventPublisherService,
    EventSubscriberService,
    EventRouterService,
    EventReplayService,
    DeadLetterService,
    RetryService,
    CorrelationService,
    SubscriptionService,
  ],
  exports: [
    WorkflowService,
    WorkflowExecutionService,
    RuleService,
    RuleEvaluationService,
    EventPublisherService,
    SubscriptionService,
  ],
})
export class AutomationModule {}
