export enum ProductionType {
  CUSTOMER_ORDER = 'CUSTOMER_ORDER',
  BATCH_PREPARATION = 'BATCH_PREPARATION',
  PREP_WORK = 'PREP_WORK',
  CENTRAL_KITCHEN = 'CENTRAL_KITCHEN',
  MANUFACTURING = 'MANUFACTURING',
  CATERING = 'CATERING',
}
