/**
 * Enterprise Analytics Foundation Platform - Domain Enums
 */

export enum AnalyticsType {
  OPERATIONAL_ANALYTICS = 'OPERATIONAL_ANALYTICS',
  BUSINESS_ANALYTICS = 'BUSINESS_ANALYTICS',
  FINANCIAL_ANALYTICS = 'FINANCIAL_ANALYTICS',
  CUSTOMER_ANALYTICS = 'CUSTOMER_ANALYTICS',
  INVENTORY_ANALYTICS = 'INVENTORY_ANALYTICS',
  EMPLOYEE_ANALYTICS = 'EMPLOYEE_ANALYTICS',
  MARKETING_ANALYTICS = 'MARKETING_ANALYTICS',
  AI_ANALYTICS = 'AI_ANALYTICS',
}

export enum MetricType {
  COUNTER = 'COUNTER',
  GAUGE = 'GAUGE',
  HISTOGRAM = 'HISTOGRAM',
  TIMER = 'TIMER',
  DISTRIBUTION = 'DISTRIBUTION',
  RATIO = 'RATIO',
  PERCENTAGE = 'PERCENTAGE',
}

export enum MetricStatus {
  PENDING = 'PENDING',
  COLLECTED = 'COLLECTED',
  AGGREGATED = 'AGGREGATED',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum AggregationStrategy {
  SUM = 'SUM',
  AVERAGE = 'AVERAGE',
  MINIMUM = 'MINIMUM',
  MAXIMUM = 'MAXIMUM',
  COUNT = 'COUNT',
  PERCENTILE = 'PERCENTILE',
  MOVING_AVERAGE = 'MOVING_AVERAGE',
}
