/**
 * Enterprise KPI Platform - Domain Enums
 */

export enum KpiType {
  FINANCIAL_KPI = 'FINANCIAL_KPI',
  OPERATIONAL_KPI = 'OPERATIONAL_KPI',
  SALES_KPI = 'SALES_KPI',
  INVENTORY_KPI = 'INVENTORY_KPI',
  CUSTOMER_KPI = 'CUSTOMER_KPI',
  EMPLOYEE_KPI = 'EMPLOYEE_KPI',
  MARKETING_KPI = 'MARKETING_KPI',
  AI_KPI = 'AI_KPI',
}

export enum TargetType {
  STATIC_TARGET = 'STATIC_TARGET',
  DYNAMIC_TARGET = 'DYNAMIC_TARGET',
  PERCENTAGE_TARGET = 'PERCENTAGE_TARGET',
  ROLLING_TARGET = 'ROLLING_TARGET',
  DEPARTMENT_TARGET = 'DEPARTMENT_TARGET',
  RESTAURANT_TARGET = 'RESTAURANT_TARGET',
  GLOBAL_TARGET = 'GLOBAL_TARGET',
}

export enum KpiStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  DEPRECATED = 'DEPRECATED',
  ARCHIVED = 'ARCHIVED',
}

export enum ThresholdStatus {
  EXCELLENT = 'EXCELLENT',
  GOOD = 'GOOD',
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL',
}
