/**
 * Enterprise AI Agent Platform - Domain Enums
 */

export enum AgentType {
  RESTAURANT_ASSISTANT = 'RESTAURANT_ASSISTANT',
  MANAGER_AGENT = 'MANAGER_AGENT',
  KITCHEN_AGENT = 'KITCHEN_AGENT',
  INVENTORY_AGENT = 'INVENTORY_AGENT',
  FINANCE_AGENT = 'FINANCE_AGENT',
  MARKETING_AGENT = 'MARKETING_AGENT',
  CUSTOMER_SUPPORT_AGENT = 'CUSTOMER_SUPPORT_AGENT',
  OPERATIONS_AGENT = 'OPERATIONS_AGENT',
  CUSTOM_AGENT = 'CUSTOM_AGENT',
}

export enum ExecutionType {
  SINGLE_STEP = 'SINGLE_STEP',
  MULTI_STEP = 'MULTI_STEP',
  PLANNING = 'PLANNING',
  REASONING = 'REASONING',
  TOOL_ORCHESTRATION = 'TOOL_ORCHESTRATION',
  HUMAN_APPROVAL = 'HUMAN_APPROVAL',
  RECOVERY = 'RECOVERY',
  PARALLEL_EXECUTION = 'PARALLEL_EXECUTION',
}

export enum MemoryType {
  WORKING_MEMORY = 'WORKING_MEMORY',
  SESSION_MEMORY = 'SESSION_MEMORY',
  LONG_TERM_MEMORY_REFERENCE = 'LONG_TERM_MEMORY_REFERENCE',
  KNOWLEDGE_MEMORY = 'KNOWLEDGE_MEMORY',
  EXECUTION_MEMORY = 'EXECUTION_MEMORY',
}

export enum AgentStatus {
  DRAFT = 'DRAFT',
  READY = 'READY',
  RUNNING = 'RUNNING',
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  ARCHIVED = 'ARCHIVED',
}

export enum StepStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  SKIPPED = 'SKIPPED',
  FAILED = 'FAILED',
  COMPENSATED = 'COMPENSATED',
}
