/**
 * Enterprise RAG Platform - Domain Enums
 */

export enum RetrievalType {
  SEMANTIC_SEARCH = 'SEMANTIC_SEARCH',
  HYBRID_SEARCH = 'HYBRID_SEARCH',
  KEYWORD_SEARCH = 'KEYWORD_SEARCH',
  METADATA_SEARCH = 'METADATA_SEARCH',
  FILTERED_SEARCH = 'FILTERED_SEARCH',
  CROSS_COLLECTION_SEARCH = 'CROSS_COLLECTION_SEARCH',
  HIERARCHICAL_RETRIEVAL = 'HIERARCHICAL_RETRIEVAL',
}

export enum ContextType {
  DOCUMENT_CONTEXT = 'DOCUMENT_CONTEXT',
  KNOWLEDGE_CONTEXT = 'KNOWLEDGE_CONTEXT',
  MENU_CONTEXT = 'MENU_CONTEXT',
  RECIPE_CONTEXT = 'RECIPE_CONTEXT',
  POLICY_CONTEXT = 'POLICY_CONTEXT',
  CONVERSATION_CONTEXT = 'CONVERSATION_CONTEXT',
  STRUCTURED_DATA_CONTEXT = 'STRUCTURED_DATA_CONTEXT',
}

export enum RetrievalStatus {
  QUEUED = 'QUEUED',
  RETRIEVING = 'RETRIEVING',
  RANKING = 'RANKING',
  ASSEMBLING = 'ASSEMBLING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum RankingStrategy {
  SIMILARITY = 'SIMILARITY',
  HYBRID = 'HYBRID',
  CROSS_ENCODER = 'CROSS_ENCODER',
  RECIPROCAL_RANK_FUSION = 'RECIPROCAL_RANK_FUSION',
  CUSTOM = 'CUSTOM',
}
