/**
 * Enterprise Embedding & Vector Platform - Domain Enums
 */

export enum VectorType {
  TEXT_EMBEDDING = 'TEXT_EMBEDDING',
  IMAGE_EMBEDDING = 'IMAGE_EMBEDDING',
  DOCUMENT_EMBEDDING = 'DOCUMENT_EMBEDDING',
  MENU_EMBEDDING = 'MENU_EMBEDDING',
  PRODUCT_EMBEDDING = 'PRODUCT_EMBEDDING',
  CUSTOMER_EMBEDDING = 'CUSTOMER_EMBEDDING',
  KNOWLEDGE_EMBEDDING = 'KNOWLEDGE_EMBEDDING',
  CUSTOM_EMBEDDING = 'CUSTOM_EMBEDDING',
}

export enum CollectionType {
  KNOWLEDGE_BASE = 'KNOWLEDGE_BASE',
  MENU = 'MENU',
  PRODUCTS = 'PRODUCTS',
  RECIPES = 'RECIPES',
  DOCUMENTS = 'DOCUMENTS',
  POLICIES = 'POLICIES',
  TRAINING = 'TRAINING',
  CONVERSATIONS = 'CONVERSATIONS',
}

export enum EmbeddingStatus {
  PENDING = 'PENDING',
  GENERATING = 'GENERATING',
  READY = 'READY',
  DEPRECATED = 'DEPRECATED',
  ARCHIVED = 'ARCHIVED',
}

export enum SimilarityMetric {
  COSINE = 'COSINE',
  DOT_PRODUCT = 'DOT_PRODUCT',
  EUCLIDEAN = 'EUCLIDEAN',
  MANHATTAN = 'MANHATTAN',
}
