/**
 * Enterprise Integration Catalog - Domain Enums
 */

export enum CatalogType {
  PAYMENT = 'PAYMENT',
  DELIVERY = 'DELIVERY',
  POS = 'POS',
  ERP = 'ERP',
  CRM = 'CRM',
  ACCOUNTING = 'ACCOUNTING',
  GOVERNMENT = 'GOVERNMENT',
  IDENTITY = 'IDENTITY',
  STORAGE = 'STORAGE',
  AI = 'AI',
  NOTIFICATION = 'NOTIFICATION',
  CUSTOM = 'CUSTOM',
}

export enum TemplateType {
  CONNECTOR_TEMPLATE = 'CONNECTOR_TEMPLATE',
  WEBHOOK_TEMPLATE = 'WEBHOOK_TEMPLATE',
  AUTHENTICATION_TEMPLATE = 'AUTHENTICATION_TEMPLATE',
  TRANSFORMATION_TEMPLATE = 'TRANSFORMATION_TEMPLATE',
  AUTOMATION_TEMPLATE = 'AUTOMATION_TEMPLATE',
}

export enum CertificationLevel {
  DRAFT = 'DRAFT',
  COMMUNITY = 'COMMUNITY',
  VERIFIED = 'VERIFIED',
  CERTIFIED = 'CERTIFIED',
  ENTERPRISE = 'ENTERPRISE',
}

export enum CompatibilityStatus {
  SUPPORTED = 'SUPPORTED',
  DEPRECATED = 'DEPRECATED',
  EXPERIMENTAL = 'EXPERIMENTAL',
  UNSUPPORTED = 'UNSUPPORTED',
}
