/**
 * Enterprise Data Transformation Platform - Domain Enums
 */

export enum TransformationType {
  INBOUND_MAPPING = 'INBOUND_MAPPING',
  OUTBOUND_MAPPING = 'OUTBOUND_MAPPING',
  SCHEMA_VALIDATION = 'SCHEMA_VALIDATION',
  NORMALIZATION = 'NORMALIZATION',
  ENRICHMENT = 'ENRICHMENT',
  FILTERING = 'FILTERING',
  PROJECTION = 'PROJECTION',
  FIELD_MAPPING = 'FIELD_MAPPING',
}

export enum MappingType {
  ONE_TO_ONE = 'ONE_TO_ONE',
  ONE_TO_MANY = 'ONE_TO_MANY',
  MANY_TO_ONE = 'MANY_TO_ONE',
  EXPRESSION_MAPPING = 'EXPRESSION_MAPPING',
  LOOKUP_MAPPING = 'LOOKUP_MAPPING',
  CONDITIONAL_MAPPING = 'CONDITIONAL_MAPPING',
  TEMPLATE_MAPPING = 'TEMPLATE_MAPPING',
}

export enum TransformationStatus {
  DRAFT = 'DRAFT',
  VALIDATED = 'VALIDATED',
  PUBLISHED = 'PUBLISHED',
  DEPRECATED = 'DEPRECATED',
  ARCHIVED = 'ARCHIVED',
}

export enum MappingResultEnum {
  SUCCESS = 'SUCCESS',
  PARTIAL = 'PARTIAL',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
}
