import { Module } from '@nestjs/common';
import {
  AuthenticationController,
  AuthorizationController,
  SecretsController,
  AuditController,
  ThreatController,
} from './infrastructure/controllers';
import { LocalSecretProvider } from './infrastructure/providers';
import {
  AuthenticationService,
  SessionService,
  TokenService,
  PasswordService,
  PasskeyService,
  MfaService,
  IdentityProviderService,
  TrustedDeviceService,
  AuthorizationService,
  RoleService,
  PermissionService,
  PolicyEngineService,
  ResourceAuthorizationService,
  DelegationService,
  PermissionInheritanceService,
  AuthorizationAuditService,
  SecretService,
  KeyManagementService,
  CertificateService,
  RotationService,
  VaultIntegrationService,
  SecretVersionService,
  EnvelopeEncryptionService,
  SecretAuditService,
  AuditService,
  ComplianceService,
  EvidenceService,
  RetentionService,
  AuditSearchService,
  ExportService,
  IntegrityVerificationService,
  ThreatDetectionService,
  BehaviorAnalysisService,
  RiskScoringService,
  IncidentService,
  AlertService,
  SecurityResponseService,
  RuleEngineService,
} from './application/services';

@Module({
  controllers: [
    AuthenticationController,
    AuthorizationController,
    SecretsController,
    AuditController,
    ThreatController,
  ],
  providers: [
    LocalSecretProvider,
    AuthenticationService,
    SessionService,
    TokenService,
    PasswordService,
    PasskeyService,
    MfaService,
    IdentityProviderService,
    TrustedDeviceService,
    AuthorizationService,
    RoleService,
    PermissionService,
    PolicyEngineService,
    ResourceAuthorizationService,
    DelegationService,
    PermissionInheritanceService,
    AuthorizationAuditService,
    SecretService,
    KeyManagementService,
    CertificateService,
    RotationService,
    VaultIntegrationService,
    SecretVersionService,
    EnvelopeEncryptionService,
    SecretAuditService,
    AuditService,
    ComplianceService,
    EvidenceService,
    RetentionService,
    AuditSearchService,
    ExportService,
    IntegrityVerificationService,
    ThreatDetectionService,
    BehaviorAnalysisService,
    RiskScoringService,
    IncidentService,
    AlertService,
    SecurityResponseService,
    RuleEngineService,
  ],
  exports: [
    AuthenticationService,
    SessionService,
    TokenService,
    AuthorizationService,
    RoleService,
    PermissionService,
    SecretService,
    KeyManagementService,
    AuditService,
    ComplianceService,
    ThreatDetectionService,
    IncidentService,
  ],
})
export class SecurityModule {}
