import { Module } from '@nestjs/common';
import { AuthenticationController, AuthorizationController, SecretsController } from './infrastructure/controllers';
import { LocalSecretProvider } from './infrastructure/providers';
import {
  AuthenticationService,
  SessionService,
  TokenService,
  PasswordService,
  PasskeyService,
  MfaService,
  IdentityProviderService,
  TrustedDeviceService,
  AuthorizationService,
  RoleService,
  PermissionService,
  PolicyEngineService,
  ResourceAuthorizationService,
  DelegationService,
  PermissionInheritanceService,
  AuthorizationAuditService,
  SecretService,
  KeyManagementService,
  CertificateService,
  RotationService,
  VaultIntegrationService,
  SecretVersionService,
  EnvelopeEncryptionService,
  SecretAuditService,
} from './application/services';

@Module({
  controllers: [
    AuthenticationController,
    AuthorizationController,
    SecretsController,
  ],
  providers: [
    LocalSecretProvider,
    AuthenticationService,
    SessionService,
    TokenService,
    PasswordService,
    PasskeyService,
    MfaService,
    IdentityProviderService,
    TrustedDeviceService,
    AuthorizationService,
    RoleService,
    PermissionService,
    PolicyEngineService,
    ResourceAuthorizationService,
    DelegationService,
    PermissionInheritanceService,
    AuthorizationAuditService,
    SecretService,
    KeyManagementService,
    CertificateService,
    RotationService,
    VaultIntegrationService,
    SecretVersionService,
    EnvelopeEncryptionService,
    SecretAuditService,
  ],
  exports: [
    AuthenticationService,
    SessionService,
    TokenService,
    AuthorizationService,
    RoleService,
    PermissionService,
    SecretService,
    KeyManagementService,
  ],
})
export class SecurityModule {}
